#!/usr/local/bin/ansible-playbook
- hosts: konductor
  gather_facts: no
  tasks:
    - import_role:
        name: build

# kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
