apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br2-enp2s0
spec:
  desiredState:
    interfaces:
    - name: br2
      description: Linux bridge with enp2s0 as a port
      type: linux-bridge
      state: up
      ipv4:
        dhcp: true
        enabled: true
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: enp2s0
