apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  generation: 2
  name: qubo-br0
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    - description: Linux bridge with eno2np1 as a port
      name: qubo-br0
      type: linux-bridge
      state: up
      ipv4:
        dhcp: false
        enabled: true
      bridge:
        options:
          stp:
            enabled: false
        port:
          - name: eno2np1
