---
# https://kubevirt.io/2020/Multiple-Network-Attachments-with-bridge-CNI.html
# https://examples.openshift.pub/kubevirt/networking/
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond
spec:
  nodeSelector:
    node-role.kubernetes.io/kubevirt: ""
  desiredState:
    interfaces:
    - name: bond0
      type: bond
      state: up
      ipv6:
        dhcp: false
        enabled: false
      ipv4:
        dhcp: false
        enabled: false
      link-aggregation:
        mode: balance-rr
        options:
          miimon: '140'
        slaves:
        - eno1np0
#       - eno2np1
#       - ens2f0
#       - ens2f1
#       - eth2
#       - eth3
---
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: linux-bridge
spec:
  nodeSelector:
    node-role.kubernetes.io/kubevirt: ""
  desiredState:
    interfaces:
    - name: br0
      description: Linux bridge with bond0 as a port
      type: linux-bridge
      state: up
      ipv6:
        dhcp: false
        enabled: false
      ipv4:
        dhcp: false
        enabled: false
      bridge:
        options:
          stp:
            enabled: true
        port:
        - name: bond0
        - name: eno2np1
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: br0
  namespace: kargo
spec:
  config: >
    {
        "cniVersion": "0.3.1",
        "name": "br0",
        "plugins": [
            {
                "type": "bridge",
                "bridge": "br0",
                "ipam": {}
            },
            {
                "type": "tuning"
            }
        ]
    }
