#!/bin/bash -x
cat <<EOF | jq .
    {
      "cniVersion": "0.3.1",
      "name": "home-network",
      "type": "bridge",
      "bridge": "br100",
      "isDefaultGateway": false,
      "forceAddress": false,
      "ipMasq": false,
      "hairpinMode": false,
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.201",
        "rangeEnd": "192.168.1.250",
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ],
        "gateway": "192.168.1.1"
      },
      "dns": {
        "nameservers": [
          "1.1.1.1"
        ]
      }
    }
EOF
