---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ccio-coreos-4.7
  namespace: kargo
spec:
  source:
    registry:
      url: "docker://quay.io/containercraft/coreos:latest"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 32Gi
