---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: fedora
spec:
  running: true
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: artemis
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            bridge: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 8192M
      networks:
      - name: eth0
        multus:
          networkName: br0
      terminationGracePeriodSeconds: 0
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containercraft/fedora:34
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #!/bin/bash -x
              echo "passwd" | passwd root --stdin
              echo "fedora" | passwd fedora --stdin
              mkdir -p /home/fedora/.ssh
              touch /home/fedora/.ssh/authorized_keys
              curl -L https://github.com/usrbinkat.keys | tee -a /home/fedora/.ssh/authorized_keys
              chown fedora:fedora /home/fedora/.ssh
              chown fedora:fedora /home/fedora/.ssh/authorized_keys
              chmod 600 /home/fedora/.ssh/authorized_keys
              sudo grubby --update-kernel=ALL --args 'cgroup_memory=1 cgroup_enable=cpuset cgroup_enable=memory systemd.unified_cgroup_hierarchy=0 intel_iommu=on iommu=pt rd.driver.pre=vfio-pci pci=realloc'
              sudo dnf -y install openssh-server qemu-guest-agent @virtualization lnav tmux vi vim
              sudo dnf -y groupinstall "Container Management"
              sudo systemctl enable --now qemu-guest-agent
              sudo systemctl enable --now libvirtd
              sudo systemctl enable --now sshd
              sudo echo 'unix_sock_group = "libvirt"' > /etc/libvirt/libvirtd.conf
              sudo echo 'unix_sock_rw_perms = "0770"' > /etc/libvirt/libvirtd.conf
              sudo usermod -aG libvirt fedora
              sudo dnf update -y
