apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: eth3
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "eth3",
      "type": "host-device",
      "device": "eth3"
    }
