kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: lan
  annotations:
    k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/lan
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "lan",
      "type": "macvtap-cni"
      "mtu": 1500
    }'
