apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default-addresses
      protocol: layer2
      addresses:
      - 192.168.1.66-192.168.1.69
