name: Workflow Dispatcher
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v3.1.0

    - name: Build Manifests
      run: |
        TERM=screen-256color ./hack/build.sh

    - name: Push Updates
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git stage -A
        git commit -m "auto updates" --all 2>&1 || true
        git push origin main

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.2.0

    - name: Validate
      run: |
        TERM=screen-256color ./hack/test.sh
